//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ShopPrac
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Order CustomAttributes)

    // *** End programmer edit section *** (Order CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OrderE", new string[] {
            "Number as \'Номер\'",
            "Status as \'Статус\'",
            "CreateDate as \'Дата оформления\'",
            "Manager as \'Менеджер\'",
            "Manager.LastName",
            "TotalSum as \'Сумма заказа\'",
            "PaymentDate as \'Дата оплаты\'",
            "ShipmentDate as \'Дата отгрузки\'"}, Hidden=new string[] {
            "Manager.LastName"})]
    [AssociatedDetailViewAttribute("OrderE", "OrderItem", "OrderItemE", true, "", "Order item", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("OrderE", "Manager", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "LastName")]
    [View("OrderL", new string[] {
            "Number as \'Номер\'",
            "Status as \'Статус\'",
            "CreateDate as \'Дата оформления\'",
            "Manager.LastName as \'Менеджер\'",
            "TotalSum as \'Стоимость заказа\'",
            "PaymentDate as \'Дата оплаты\'",
            "ShipmentDate as \'Дата отгрузки\'"})]
    public class Order : IIS.ShopPrac.Document
    {
        
        private IIS.ShopPrac.OrderStatus fStatus = IIS.ShopPrac.OrderStatus.New;
        
        private System.DateTime fShipmentDate;
        
        private System.DateTime fPaymentDate;
        
        private IIS.ShopPrac.Employee fManager;
        
        private IIS.ShopPrac.DetailArrayOfOrderItem fOrderItem;
        
        // *** Start programmer edit section *** (Order CustomMembers)

        // *** End programmer edit section *** (Order CustomMembers)

        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Order.Status CustomAttributes)

        // *** End programmer edit section *** (Order.Status CustomAttributes)
        public virtual IIS.ShopPrac.OrderStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Order.Status Get start)

                // *** End programmer edit section *** (Order.Status Get start)
                IIS.ShopPrac.OrderStatus result = this.fStatus;
                // *** Start programmer edit section *** (Order.Status Get end)

                // *** End programmer edit section *** (Order.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.Status Set start)

                // *** End programmer edit section *** (Order.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Order.Status Set end)

                // *** End programmer edit section *** (Order.Status Set end)
            }
        }
        
        /// <summary>
        /// ShipmentDate.
        /// </summary>
        // *** Start programmer edit section *** (Order.ShipmentDate CustomAttributes)

        // *** End programmer edit section *** (Order.ShipmentDate CustomAttributes)
        public virtual System.DateTime ShipmentDate
        {
            get
            {
                // *** Start programmer edit section *** (Order.ShipmentDate Get start)

                // *** End programmer edit section *** (Order.ShipmentDate Get start)
                System.DateTime result = this.fShipmentDate;
                // *** Start programmer edit section *** (Order.ShipmentDate Get end)

                // *** End programmer edit section *** (Order.ShipmentDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.ShipmentDate Set start)

                // *** End programmer edit section *** (Order.ShipmentDate Set start)
                this.fShipmentDate = value;
                // *** Start programmer edit section *** (Order.ShipmentDate Set end)

                // *** End programmer edit section *** (Order.ShipmentDate Set end)
            }
        }
        
        /// <summary>
        /// PaymentDate.
        /// </summary>
        // *** Start programmer edit section *** (Order.PaymentDate CustomAttributes)

        // *** End programmer edit section *** (Order.PaymentDate CustomAttributes)
        public virtual System.DateTime PaymentDate
        {
            get
            {
                // *** Start programmer edit section *** (Order.PaymentDate Get start)

                // *** End programmer edit section *** (Order.PaymentDate Get start)
                System.DateTime result = this.fPaymentDate;
                // *** Start programmer edit section *** (Order.PaymentDate Get end)

                // *** End programmer edit section *** (Order.PaymentDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.PaymentDate Set start)

                // *** End programmer edit section *** (Order.PaymentDate Set start)
                this.fPaymentDate = value;
                // *** Start programmer edit section *** (Order.PaymentDate Set end)

                // *** End programmer edit section *** (Order.PaymentDate Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (Order.TotalSum CustomAttributes)

        // *** End programmer edit section *** (Order.TotalSum CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (Order.TotalSum Get)

                return 0;
                // *** End programmer edit section *** (Order.TotalSum Get)
            }
            set
            {
                // *** Start programmer edit section *** (Order.TotalSum Set)

                // *** End programmer edit section *** (Order.TotalSum Set)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Order.Manager CustomAttributes)

        // *** End programmer edit section *** (Order.Manager CustomAttributes)
        [PropertyStorage(new string[] {
                "Manager"})]
        public virtual IIS.ShopPrac.Employee Manager
        {
            get
            {
                // *** Start programmer edit section *** (Order.Manager Get start)

                // *** End programmer edit section *** (Order.Manager Get start)
                IIS.ShopPrac.Employee result = this.fManager;
                // *** Start programmer edit section *** (Order.Manager Get end)

                // *** End programmer edit section *** (Order.Manager Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.Manager Set start)

                // *** End programmer edit section *** (Order.Manager Set start)
                this.fManager = value;
                // *** Start programmer edit section *** (Order.Manager Set end)

                // *** End programmer edit section *** (Order.Manager Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Order.OrderItem CustomAttributes)

        // *** End programmer edit section *** (Order.OrderItem CustomAttributes)
        public virtual IIS.ShopPrac.DetailArrayOfOrderItem OrderItem
        {
            get
            {
                // *** Start programmer edit section *** (Order.OrderItem Get start)

                // *** End programmer edit section *** (Order.OrderItem Get start)
                if ((this.fOrderItem == null))
                {
                    this.fOrderItem = new IIS.ShopPrac.DetailArrayOfOrderItem(this);
                }
                IIS.ShopPrac.DetailArrayOfOrderItem result = this.fOrderItem;
                // *** Start programmer edit section *** (Order.OrderItem Get end)

                // *** End programmer edit section *** (Order.OrderItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.OrderItem Set start)

                // *** End programmer edit section *** (Order.OrderItem Set start)
                this.fOrderItem = value;
                // *** Start programmer edit section *** (Order.OrderItem Set end)

                // *** End programmer edit section *** (Order.OrderItem Set end)
            }
        }
        
        // *** Start programmer edit section *** (Order.Cancel CustomAttributes)

        // *** End programmer edit section *** (Order.Cancel CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Cancel()
        {
            // *** Start programmer edit section *** (Order.Cancel method implementation)

            return;
            // *** End programmer edit section *** (Order.Cancel method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OrderE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderE", typeof(IIS.ShopPrac.Order));
                }
            }
            
            /// <summary>
            /// "OrderL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderL", typeof(IIS.ShopPrac.Order));
                }
            }
        }
    }
}
