//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ShopPrac
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СостояниеЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (OrderStatus CustomAttributes)

    // *** End programmer edit section *** (OrderStatus CustomAttributes)
    public enum OrderStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.New CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.New CustomAttributes)
        [Caption("Новый")]
        New,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.Paid CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Paid CustomAttributes)
        [Caption("Оплаченный")]
        Paid,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.Cancelled CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Cancelled CustomAttributes)
        [Caption("Отмененный")]
        Cancelled,
    }
}
